language: node_js
sudo: false
node_js:
- stable
- 6
addon:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
